project_id = "inzcqenjspikefbsoagh"

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:8080/auth/callback"]

[auth.external.google]
enabled = true
client_id = "621758460107-42k0ko28qkejcllcraf4ns3lrdug4sja.apps.googleusercontent.com"
secret = "env(GOOGLE_CLIENT_SECRET)"